import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FavoritesProvider } from '@/lib/store';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <FavoritesProvider>
          <nav className="main-nav">
            <div className="container">
              <a href="/" className="nav-logo">2026 Beach Planner 🏖️</a>
              <a href="/favorites" className="nav-link">Favorites ♥</a>
            </div>
          </nav>
          {children}
        </FavoritesProvider>
      </body>
    </html>
  );
}
